version: '3.8'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: event_manager
      POSTGRES_USER: event_user
      POSTGRES_PASSWORD: event_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  frontend:
    build:
      context: ./events-frontend      
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "5173:5173"
    depends_on:
      - web
    volumes:
      - ./events-frontend:/app
    #  - /app/node_modules
    networks:
      - default

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_NAME=event_manager
      - DATABASE_USER=event_user
      - DATABASE_PASSWORD=event_manager
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    networks:
      - default
    env_file:
        - .env
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
